### ISSUE TITLE
Overlay cant recognize cooldown nor party in game. 

### ISSUE THREAD

**Issue by sasahara00** [priprii/GenshinOverlay#3] opened 2020-10-17 13:55 UTC
https://imgur.com/a/7e2xNWP

set up as instructed .

character change or skill cooldown is not recognize by the program.
played with Cooldown Properties but still no use. 
not sure what the problem is.

**Comment by priprii** [comment] 2020-10-17 16:08
What resolution & window mode are you using?
Do the bars display at all after saving config and giving focus to the game?
If the above is true: If you set "Sel. Offset" to a different value, does the bar change position when you change character?

**Comment by Yentis** [comment] 2020-10-17 17:20
Same issue here, it's just generally failing to recognize cooldowns as they rarely trigger and the cooldown bar also lasts way longer than it should.
![image](https://user-images.githubusercontent.com/17981128/96349131-d393d680-10ad-11eb-8d2a-dfedf35c87e3.png)
![image](https://user-images.githubusercontent.com/17981128/96349135-d7bff400-10ad-11eb-8fe8-aa8c9e0b52bb.png)

**Comment by priprii** [comment] 2020-10-17 17:40
Sounds like an issue with the way you have the cooldown text rectangle setup.
Do note that I did not test whether each template actually works well as I don't have time to test with every resolution, so the auto setup should not be entirely relied on, they may require a little manual adjustment. Most of my testing was done with resolution set to 1280x768 so that's the only one I can be certain of that should work well.

Could you post a picture with the config active.
Also provide the same info as I mentioned in the comment above.

**Comment by Yentis** [comment] 2020-10-17 17:53
Running windowed borderless at 2560x1440, I set all the configs manually.
After adjusting the dots like you said it's now detecting character switching properly but the issue with cooldowns persist.

New config:
![image](https://user-images.githubusercontent.com/17981128/96349827-63d41a80-10b2-11eb-8183-ebcd94586a7e.png)

**Comment by tinbtb** [comment] 2020-10-17 17:55
Can confirm that cooldown is not detected as of 1.1 neither for my native 1440p nor for 1080p. "Sel offset" shows that the character selection detection works.
![image](https://user-images.githubusercontent.com/63807414/96349855-f2e53080-10ba-11eb-8079-3015b0092afe.png)

**Comment by priprii** [comment] 2020-10-17 17:58
tinbtb, you'll need to setup the dots for party size 2 & 3.

Yentis, if your issue is with accuracy of the cooldown time, try increasing the Confidence value to around 90%. This may delay the cooldown starting a bit (especially on lighter backgrounds and if you're not moving the camera much) but it will produce more accurate results.

**Comment by Yentis** [comment] 2020-10-17 18:05
I've recorded a video for clarity, the issue is that it doesn't trigger usually and if it does the duration is inaccurate:
https://mega.nz/file/tpc31SrQ#B_4vdPN4tiKpdE_ZMyqlll66rI5yXBwghk9fC4ZIBk0

**Comment by tinbtb** [comment] 2020-10-17 18:29
> tinbtb, you'll need to setup the dots for party size 2 & 3 even if you're not using smaller party size.

For some reason the cooldown was never detected for me even for 1280x768 and dots positions set by default.

![image](https://user-images.githubusercontent.com/63807414/96350736-c2ec5c00-10bf-11eb-8103-765b5df10e24.png)

**Comment by priprii** [comment] 2020-10-17 18:58
I made a new version (v1.2) which includes a debug option.
Could you run that version with the same config and press the "Debug" button and post the results here.

It will copy the message box contents to your clipboard, so you can just paste that into here.
It will also create a "debug" folder in the GenshinOverlay directory with images of the OCR process, you can upload the images here.

**Comment by Yentis** [comment] 2020-10-17 19:12
Confidence is 94% but it's ignoring the value, in config the confidence is set to 80%.

Party Size (1 to 4): 4
Selected Character (1 to 4): Slot#2
OCR Text Detected: 25.8
Assumed Cooldown: 0
Confidence: 94%

![00_input](https://user-images.githubusercontent.com/17981128/96351675-60925c00-10bd-11eb-97ab-a25a8c53e4da.png)
![01_grayscale](https://user-images.githubusercontent.com/17981128/96351676-612af280-10bd-11eb-974d-428992021510.png)
![02_scale](https://user-images.githubusercontent.com/17981128/96351677-612af280-10bd-11eb-9cad-df3cb69de671.png)
![03_binarize](https://user-images.githubusercontent.com/17981128/96351678-612af280-10bd-11eb-82cd-7c5061364f96.png)
![04_invert_True](https://user-images.githubusercontent.com/17981128/96351679-61c38900-10bd-11eb-9c65-629bf8684b6d.png)
![05_removenoise](https://user-images.githubusercontent.com/17981128/96351680-61c38900-10bd-11eb-9b64-10330282eeb4.png)
![06_border](https://user-images.githubusercontent.com/17981128/96351681-61c38900-10bd-11eb-9bdf-07798af526d5.png)

**Comment by tinbtb** [comment] 2020-10-17 19:14
![image](https://user-images.githubusercontent.com/63807414/96351723-0649c900-10c6-11eb-9d6b-7f1e94ab043a.png)

![05_removenoise](https://user-images.githubusercontent.com/63807414/96351730-0ba71380-10c6-11eb-8bc2-dd3cd714173e.png)
![06_border](https://user-images.githubusercontent.com/63807414/96351731-0c3faa00-10c6-11eb-9a54-320277eb89e6.png)
![00_input](https://user-images.githubusercontent.com/63807414/96351732-0c3faa00-10c6-11eb-8f29-cb9cbea5185e.png)
![01_grayscale](https://user-images.githubusercontent.com/63807414/96351733-0cd84080-10c6-11eb-816c-0b3b6578b687.png)
![02_scale](https://user-images.githubusercontent.com/63807414/96351734-0cd84080-10c6-11eb-8ead-8c450ce07929.png)
![03_binarize](https://user-images.githubusercontent.com/63807414/96351735-0cd84080-10c6-11eb-8f2e-8869c662d1b2.png)
![04_invert_True](https://user-images.githubusercontent.com/63807414/96351736-0d70d700-10c6-11eb-94e7-8f013ea4abb7.png)

**Comment by priprii** [comment] 2020-10-17 19:19
Okay we can rule out the issue being with the OCR engine.

The code for this bit is:

```
    ocrText = page.GetText().Trim();
    Confidence = page.GetMeanConfidence();
    if(Confidence >= Config.OCRMinimumConfidence) {
        Text = ocrText;
        if(decimal.TryParse(ocrText, out decimal cooldown)) {
            if(cooldown < Config.CooldownMaxPossible) {
                return cooldown;
            }
        }
    }
```

The "ocrText" here is correctly set to the value, but parsing it to decimal is failing.
Are either of you from the EU? I imagine it's a culture issue with TryParse.

**Comment by Yentis** [comment] 2020-10-17 19:23
Yeah I'm from the EU

**Comment by priprii** [comment] 2020-10-17 19:25
It's odd because I'm pretty sure TryParse is culture invariant by default but I will try making a change to it.

**Comment by tinbtb** [comment] 2020-10-17 19:29
My regional format was "Russian" and yes it uses commas for decimal separation. Changed to English (US) and it works now.

**Comment by priprii** [comment] 2020-10-17 19:31
v1.3 should hopefully fix this issue, thanks for helping me with testing.

**Comment by Yentis** [comment] 2020-10-17 19:34
That did it 👍 
![image](https://user-images.githubusercontent.com/17981128/96352031-89682080-10c0-11eb-9b18-7c24f0019a0b.png)

**Comment by priprii** [comment] 2020-10-17 19:40
Good to see!
Going to close this now.
sasahara00, open another issue if you're still having problems.

**Closed by priprii** 2020-10-17 19:40 UTC
Labels: question
